___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [7]:
import numpy as np


#### Create an array of 10 zeros 

In [4]:
array = np.zeros(10)

#### Create an array of 10 ones

In [5]:
array = np.ones(10)

#### Create an array of 10 fives

In [6]:
array = np.ones(10)
array = 5

#### Create an array of the integers from 10 to 50

In [40]:
array = np.random.rand(10,51)

#### Create an array of all the even integers from 10 to 50

In [41]:
array = np.arange(10,51,2)


#### Create a 3x3 matrix with values ranging from 0 to 8

In [42]:
array = np.arange(0,9).reshape(3,3)


#### Create a 3x3 identity matrix

In [43]:
array = np.eye(3)

#### Use NumPy to generate a random number between 0 and 1

In [48]:
array = np.random.rand(1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [49]:
array = np.random.randn(25)

#### Create the following matrix:

In [55]:
array = np.arange(1,101).reshape(10,10)/100

#### Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
array = np.arange(1,21).reshape(4,5)/20

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [60]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [40]:
mat[3:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [50]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [51]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [64]:
mat[:,0:5].sum(axis = 0)


array([55, 60, 65, 70, 75])

# Great Job!