In [2]:
import numpy as py


In [7]:
my_list = [1 ,2 ,3]
py.array(my_list)

array([1, 2, 3])

In [9]:
py.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
py.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
py.ones(2)

array([ 1.,  1.])

In [15]:
py.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
py.random.randn